language: python

os:
  - linux

sudo: false

cache: pip

python:
  - "3.5"

script:
  - 'python setup.py test --tox-args="-e$TOX_ENV"'

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=pypy3
  - TOX_ENV=docs
  - TOX_ENV=pep8

matrix:
  include:
    - python: "nightly"
      env: TOX_ENV=py36
  allow_failures:
    - python: "nightly"
    - env: TOX_ENV=py26
    - env: TOX_ENV=py36
    - env: TOX_ENV=pep8
  fast_finish: true


